// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchGroupData(arg1) {
  return window['go']['groupbinder']['GroupBinder']['FetchGroupData'](arg1);
}

export function SettingGroupName(arg1, arg2) {
  return window['go']['groupbinder']['GroupBinder']['SettingGroupName'](arg1, arg2);
}

export function StarGroupChat(arg1) {
  return window['go']['groupbinder']['GroupBinder']['StarGroupChat'](arg1);
}
