// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {groupbinder} from '../models';

export function StarGroupChat(arg1:groupbinder.StartGroupChatData):Promise<void>;
