// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StarGroupChat(arg1) {
  return window['go']['groupbinder']['GroupBinder']['StarGroupChat'](arg1);
}
