// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {userapi} from '../models';

export function UserProfile(arg1:string):Promise<userapi.UserProfile>;
