// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function UserProfile(arg1) {
  return window['go']['userbinder']['UserBinder']['UserProfile'](arg1);
}
