// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function SyncConvList(arg1:string):Promise<Array<chat.ConvItem>>;

export function SyncConvMessages(arg1:string):Promise<Array<chat.ConvItem>>;
