// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {conv} from '../models';

export function SyncConvList(arg1:string):Promise<Array<conv.ConvItem>>;

export function SyncConvMessages(arg1:string):Promise<Array<conv.ConvItem>>;
