// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SyncConvList(arg1) {
  return window['go']['syncbinder']['SyncBinder']['SyncConvList'](arg1);
}

export function SyncConvMessages(arg1) {
  return window['go']['syncbinder']['SyncBinder']['SyncConvMessages'](arg1);
}
