// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearUnreadCount(arg1) {
  return window['go']['convbinder']['ConvBinder']['ClearUnreadCount'](arg1);
}
