// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchNextMsgs(arg1) {
  return window['go']['msgbinder']['MsgBinder']['FetchNextMsgs'](arg1);
}
