// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Conn2Engine(arg1) {
  return window['go']['main']['App']['Conn2Engine'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function SendMsg(arg1) {
  return window['go']['main']['App']['SendMsg'](arg1);
}

export function WailsCtx() {
  return window['go']['main']['App']['WailsCtx']();
}
