// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {preinld} from '../models';
import {context} from '../models';

export function Conn2Engine(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function SendMsg(arg1:preinld.MsgSendData):Promise<void>;

export function WailsCtx():Promise<context.Context>;
